name: Build, Test and Deploy in QA

on:
  push:
    branches:
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i --openssl-legacy-provider
      - name: Build modules
        run: npm run build --openssl-legacy-provider